"""What each Space Duel RAM variable is for.

The alias table in spaceduel_defines.asm is recovered mechanically (see
rammap.py); this file supplies the prose.  Descriptions are Atari's own,
taken from the trailing comments on the .BLKB declarations in ASTRD2.MAC,
the equates in AS2DEC.MAC, the sound channel arrays in AS2POK.MAC and the
coin variables in COIN65.MAC, rewritten in sentence case and expanded with
the array lengths and bit encodings the source states elsewhere.

Two things the reader needs to know about the names themselves:

  * DEC MACRO-65 symbols are significant to 6 characters, so a few names
    arrive truncated (CMSBSE is CMSBSET, PL0ARE is PL0AREA).

  * An address is named after whichever symbol resolves to it, and Atari's
    sources define plenty of *constants* whose value happens to equal a low
    RAM address.  Where such a constant outranks the real variable, the
    entry opens with the cell's true identity - "VGLIST+1" and so on - and
    carries the COLLIDES marker, which lookup() returns as a flag.

Keys are alias names; ADDR is the address the name is expected to land on,
and emit_defines.py warns if the recovered map disagrees, so this file
cannot drift silently away from rammap.py.
"""

COLLIDES = "@"          # leading marker: the alias name is not this cell's variable

# name -> (expected address, description)
DOCS = {

# ------------------------------------------------------------------ zero page
"VGBRIT":  (0x0000, "Vector brightness used by VGSTAT: 0 = off, $F0 = maximum, in steps of $20."),
"VGLIST":  (0x0001, "AVG display-list write pointer, 2 bytes; Add2WordsToVector stores through it with STA (VGLIST),Y."),
"EAC2":    (0x0002, COLLIDES + "VGLIST+1, the high byte of the display-list write pointer. EAC2 is AS2DEC's EAROM C2 control bit."),
"XCOMP":   (0x0003, "X component scratch for the vector builders, 4 bytes ($03-$06)."),
"RED":     (0x0004, COLLIDES + "XCOMP+1. RED is the colour constant 4."),
"CHAN3V":  (0x0005, COLLIDES + "XCOMP+2. CHAN3V is the POKEY channel 3 volume register offset."),
"TWOPI":   (0x0006, COLLIDES + "XCOMP+3. TWOPI is the angle-table constant 6."),
"TEMP1":   (0x0007, "General scratch, 3 bytes ($07-$09); the self-test uses all three. TEMP1C is TEMP1+2."),
"EACE":    (0x0008, COLLIDES + "TEMP1+1. EACE is the EAROM chip-enable bit, 8."),
"TEMP2":   (0x000A, "General scratch, 2 bytes ($0A-$0B)."),
"POTGO":   (0x000B, COLLIDES + "TEMP2+1. POTGO is the POKEY pot-scan register offset $0B."),
"TEMP3":   (0x000C, "General scratch, 4 bytes ($0C-$0F); by convention TEMP3 holds X and TEMP3+1 holds Y. TEMP3C is +2, TEMP3D is +3."),
"FOURPI":  (0x000D, COLLIDES + "TEMP3+1. FOURPI is the angle-table constant 13 decimal."),
"SKCTL":   (0x000F, COLLIDES + "TEMP3+3. SKCTL is the POKEY serial-control register offset $0F."),
"TEMP4":   (0x0010, "General scratch, 3 bytes ($10-$12)."),
"NMROCK":  (0x0011, COLLIDES + "TEMP4+1. NMROCKS is the asteroid slot count, 17 decimal."),
"TEMP5":   (0x0013, "General scratch byte."),
"TEMP6":   (0x0014, "General scratch byte."),
"TEMP7":   (0x0015, "General scratch byte."),
"TEMP7B":  (0x0016, "General scratch byte, paired with TEMP7."),
"TEMP8":   (0x0017, "General scratch byte."),
"TEMP9":   (0x0018, "General scratch byte."),
"TEMP10":  (0x0019, "General scratch byte."),
"TEMP11":  (0x001A, "General scratch byte."),
"TEMP12":  (0x001B, "General scratch byte."),
"TEMPA":   (0x001C, "General scratch byte."),
"TEMPB":   (0x001D, "General scratch byte."),
"TEMPC":   (0x001E, "General scratch byte."),
"ZSAUCE":  (0x001F, COLLIDES + "$TCMFLG, the two-coin-minimum flag (COIN65.MAC). ZSAUCER is the saucer's index in the object arrays."),
"DIAGBI":  (0x0020, COLLIDES + "$$CRDT, the credit total (COIN65.MAC). DIAGBIT is the diagnostic-step bit $20 in In0."),
"ZSHIP":   (0x0021, COLLIDES + "$INTCT, the coin routine's interrupt counter. ZSHIP is the first ship's object index."),
"ZPAIR":   (0x0023, COLLIDES + "$BC, bonus coins earned. ZPAIR is the bound pair's object index."),
"ZMINE":   (0x0024, COLLIDES + "$CMODE, the coin mode. ZMINES is the first mine's object index."),
"ROTENG":  (0x0028, COLLIDES + "$CCTIM+1, the coin-counter timers (3 bytes from $27). ROTENG is the rotational-energy constant, 40 decimal."),
"ZP1MIN":  (0x002C, COLLIDES + "$PSTSL+2, the post-coin slam timers (3 bytes from $2A). ZP1MINES is player 1's first torpedo index."),
"ZLAST":   (0x002F, COLLIDES + "$CNSTT+2, the coin status and timers (3 bytes from $2D). ZLAST is the last object index."),
"LANGBT":  (0x0030, COLLIDES + "$USE, positive while the coin routine is running. LANGBTS is the language bit mask $30 in OPTN1."),
"INTRPT":  (0x0032, "Coin-routine scratch. Beware: elsewhere the ROM reads INTRPT,X purely as SCORE+1,X - see NOTES_score.md."),
"SYNC":    (0x0033, "Coin-routine scratch. Beware: elsewhere the ROM reads SYNC,X purely as SCORE+2,X."),
"GAME":    (0x0034, "Selected game variation, 0-3 internally, one less than the number shown on screen. MAXGAME is 3, ALONEGAME 1 (one ship), TWINGAME 3 (space station, one player drives both)."),
"ATRACT":  (0x0035, "Positive while a game is running, zero in attract mode. Also SAVTOP: RAM from here up need not survive between games."),
"UPDINT":  (0x0036, "Which initial, 0 1 or 2, is being selected; 2 bytes, one per player."),
"UPDFLG":  (0x0038, "Positive when this player has set a new high score; 2 bytes, one per player."),
"SCORE":   (0x003A, "Player scores in BCD, 3 bytes each (low, middle, high) for players 0 and 1, so $3A-$3F."),
"MAXSPE":  (0x003F, COLLIDES + "SCORE+5, the high byte of player 1's score. MAXSPEED is the velocity clamp $3F."),
"CMBSCORE": (0x0040, "Combined score for the cooperative games, 3 bytes BCD; the score block $3A-$42 is staged as a unit before UpdateHighScoreTable."),
"GENDING": (0x0043, "Delay before the game ends when non-zero, counting up towards zero. IGENDING ($40) is the initial value."),
"FRAME":   (0x0044, "Free-running frame counter, 3 bytes."),
"HITS":    (0x0047, "Lives remaining, one byte per player; zero in attract mode."),
"LASTSW":  (0x0049, "Last control-switch reading, one byte per ship."),
"XINCL":   (0x004B, "Low byte of each ship's X velocity, one per ship; the high byte is XINC+ZSHIP."),
"YINCL":   (0x004D, "Low byte of each ship's Y velocity, one per ship."),
"TOGGLE":  (0x004F, "Per-ship toggle flags; D7 (SHLDON, $80) means the shield is up."),
"TOGDRONE": (0x0051, "D7 set when the second ship is a computer-flown drone."),
"TOGCOMB": (0x0052, "D7 set when the two players draw on one shared pool of lives."),
"SCRFUL":  (0x0053, "D7 set when the screen already holds the maximum number of objects."),
"KLMOFF":  (0x0054, "D7 = killer mines are to leave the screen, D6 = comets are to leave."),
"TSTBYTE": (0x0055, "Guard byte, there to catch ENMOFF being clobbered from above."),
"POINT":   (0x0056, "Sound engine: per-channel offset into the sound data tables, 16 channels; 0 means the channel is idle."),
"MXSPKT":  (0x0060, COLLIDES + "POINT+10, sound channel 10's table pointer. MXSPKTIME is the spark-timer maximum $60."),
"CURRENT": (0x0066, "Sound engine: the value currently being output on each of the 16 channels."),
"COUNT":   (0x0076, "Sound engine: changes remaining in the current step, 16 channels."),
"COCKBI":  (0x0080, COLLIDES + "COUNT+10. COCKBIT is the cocktail-cabinet bit $80 read at CABERE ($0907)."),
"FRAMES":  (0x0086, "Sound engine: frames until this channel's next change, 16 channels."),
"SINDEX":  (0x0096, "Sound engine: index of the channel INISOU and MODSND are currently servicing."),
"OBJ":     (0x0097, "Object table, 17 asteroid and explosion slots. 0 = slot free; otherwise bits 0-2 give the size (1 small, 2 medium, 4 large) and bits 3-6 the picture number."),
"OBCOMETS": (0x00A8, "Object table continues: 8 comet and dwarf slots."),
"OBKLMINES": (0x00B0, "Object table: 6 killer-mine slots."),
"OBSAUCER": (0x00B6, "Object table: 2 saucer slots."),
"OBSHIP":  (0x00B8, "Object table: 2 player-ship slots; SHPALIVE (2) marks a live ship."),
"OBPAIR":  (0x00BA, "Object table: the single bound-pair slot, the rotating bar of the space-station games."),
"OBMINES": (0x00BB, "Object table: shots start here, with 4 computer mines (OBCOMINES names the same cell)."),
"OBP0MINES": (0x00BF, "Object table: player 0's 4 torpedoes."),
"OBP1MINES": (0x00C3, "Object table: player 1's 4 torpedoes."),
"EASRCE":  (0x00C7, "EAROM transfer source pointer, 2 bytes."),
"KLMINC":  (0x00C9, "Killer-mine colour, which is the number of shots absorbed so far minus one; 6 mines."),
"DIFCTY":  (0x00CF, "Difficulty value governing how soon saucers start."),
"OPTN1":   (0x00D0, "Option switches read from POKEY 1: D7-D6 bonus level, D5-D4 language, D3-D2 difficulty, D1-D0 lives."),
"LANG":    (0x00D1, "Selected language, taken from OPTN1 bits D5-D4."),
"DIFF":    (0x00D2, "Difficulty level, taken from the option switches."),
"SAUMIN":  (0x00D3, "Minimum velocity of each saucer, one byte per saucer. Note $D3-$D5 are also read as HSCORE-3 by the high-score shift-down."),
"ROCKMIN": (0x00D5, "Minimum rock velocity, 2 bytes (plus and minus)."),
"ROCKMAX": (0x00D7, "Maximum rock velocity, 2 bytes. SAVZTOP, the end of the must-be-preserved block, follows at $D9."),
"NXTBON":  (0x00D9, "Score at which the next bonus life falls due, 2 bytes. Also SAVZTOP."),
"BONLVA":  (0x00DB, "Bonus level amount: the score step between bonus lives."),
"ATSTG":   (0x00DC, "Attract-mode stage flag."),
"HSCORE":  (0x00DD, "High score table: 3 BCD bytes x 5 entries x 4 game variants, 60 bytes ($DD-$118)."),
"BGSHEN":  (0x00F0, COLLIDES + "HSCORE+$13. BGSHENG is the full-shield energy value $F0."),

# ----------------------------------------------------------------- stack page
"INITL":   (0x0119, "Initials for the high score table: 3 characters x 5 entries x 4 variants, 60 bytes ($119-$154)."),
"SPINT":   (0x0155, "Extra initials for the two-player space-station game, 3 x 5 = 15 bytes."),
"EABUF":   (0x0164, "EAROM read and write staging buffer, 32 bytes ($164-$183)."),
"EAZFLG":  (0x0184, "Non-zero asks the EAROM handler to zero the whole device."),
"EAREQU":  (0x0185, "EAROM access request bitmap, one bit per batch of data: D0 is batch 0 through D7 batch 7; a set bit requests that batch."),
"EARWRQ":  (0x0186, "Access type for each bit of EAREQU: 0 = read, 1 = write."),
"EABAD":   (0x0187, "Per-batch outcome, matching EAREQU bit for bit: 0 = success, 1 = failure."),
"EAFLG":   (0x0188, "Control byte for one EAROM operation: D7 erase, D6 write, D5 read, D4 zero the device when D6 is also set."),
"EABC":    (0x0189, "Byte index into the buffer addressed by EASRCE."),
"EAX":     (0x018A, "Byte offset within the EAROM for the next access."),
"EACNT":   (0x018B, "Byte offset within the EAROM for the last access."),
"EASEL":   (0x018C, "Index code identifying the batch operation in progress."),
"EACS":    (0x018D, "Running checksum over the batch."),
"ONTIME":  (0x018E, "Bookkeeping: total time the cabinet has been powered on, 4 bytes."),
"BONTIME": (0x0192, "Bookkeeping: bonus time, 4 bytes; reused as scratch during EAROM transfers."),
"PLAYTIME": (0x0196, "Bookkeeping: play time, 4 bytes for each of the 4 one- and two-player variants."),
"GAMES1":  (0x01A6, "Bookkeeping: games played, 3 bytes for each of the 4 variants."),
"THRENG":  (0x01E0, COLLIDES + "not a variable at all: THRENG is the constant $F0*2, the thrust energy of the rotating pair. Its value lands inside the 6502 stack."),

# ------------------------------------------------------------------- game RAM
"XINC":    (0x0200, "X velocity of every object, 50 entries, Atari's S8999.BBB format (signed, 3 fractional bits)."),
"YINC":    (0x0232, "Y velocity of every object, 50 entries, S9999.BBB format."),
"NROCKS":  (0x0264, "Number of rocks currently on screen."),
"ENMDEL":  (0x0265, "Frames until this ship becomes a target again, one per ship."),
"EDELAY":  (0x0267, "Delay before an enemy enters or fires, one per saucer."),
"SENMDEL": (0x0269, "Starting value loaded into ENMDEL, one per ship."),
"RTIMER":  (0x026B, "Rock timer: at 0 a saucer is sent in regardless of how many rocks remain. One per ship."),
"SDELAY":  (0x026D, "Delay before this ship is put back; $80 means the ship was just destroyed. One per ship."),
"ETIMER":  (0x026F, "Counts down to 0, at which point the saucer may return. One per saucer."),
"RDELAY":  (0x0271, "Delay before more rocks are added."),
"THUMP3":  (0x0272, "Starting value for the THUMP2 heartbeat-sound counter."),
"SHLDENG": (0x0273, "Shield energy remaining, upper byte, one per ship; BGSHENG ($F0) is a full charge."),
"LSHLDENG": (0x0275, "Shield energy remaining, lower byte; MINSHENG ($18) is the minimum useful upper byte."),
"CSPEED":  (0x0277, "Comet speed, 8 comets."),
"KSPEED":  (0x027F, "Killer-mine speed, 6 mines."),
"CANGCH":  (0x0285, "Per-frame change in comet heading, low byte, 8 comets."),
"KANGCH":  (0x028D, "Per-frame change in killer-mine heading, low byte, 6 mines."),
"CANGLH":  (0x0293, "Comet heading, high byte, 8 comets."),
"KANGLH":  (0x029B, "Killer-mine heading, high byte, 6 mines."),
"ANGLE":   (0x02A1, "Saucer rotation angle, 2 saucers."),
"SANGLE":  (0x02A3, "Ship orientation angle, 2 ships."),
"CANGLL":  (0x02A5, "Comet heading, low byte, 8 comets."),
"KANGLL":  (0x02AD, "Killer-mine heading, low byte, 6 mines."),
"BANGLE":  (0x02B3, "Rotating bar angle, high byte."),
"BANGLL":  (0x02B4, "Rotating bar angle, low byte."),
"OBJXH":   (0x02B5, "X position of every object, high byte, 50 entries."),
"OBJYH":   (0x02E7, "Y position of every object, high byte, 50 entries."),
"ISNSP2":  (0x0319, "Initial speed for the second sound circuit. Declared but never referenced by the shipped ROM."),
"SNDBA2":  (0x031A, "Base value for the second sound circuit. Declared but never referenced by the shipped ROM."),
"SNDSP2":  (0x031B, "Speed for the second sound circuit. Declared but never referenced by the shipped ROM."),
"SPARKANGLE": (0x031C, "Angle of each of the 4 spark rays arcing between the paired ships."),
"OBJXL":   (0x0320, "X position of every object, low byte, 50 entries, 99999.BBB format."),
"OBJYL":   (0x0352, "Y position of every object, low byte, 50 entries."),
"UWBAR":   (0x0384, "Bar rotation speed, upper byte."),
"LWBAR":   (0x0385, "Bar rotation speed, lower byte."),
"BXINCL":  (0x0386, "Bar centre-of-mass X velocity, low byte; the high byte is BXINC, which is XINC+ZPAIR."),
"BYINCL":  (0x0387, "Bar centre-of-mass Y velocity, low byte; the high byte is BYINC, which is YINC+ZPAIR."),
"PRTDAMAGE": (0x0388, "Partial damage taken when non-zero; MXPTDAMAGE ($80) is the maximum, counting negative. One per ship."),
"COLLIS":  (0x038A, "Last object this ship collided with; COLBIT ($80) is shifted in each frame. One per ship."),
"STRADDLE": (0x038C, "D7 set when the object straddles the X wrap, D6 when it straddles Y."),
"COMOFF":  (0x038D, "-1 while the comets are being sent off screen."),
"OWNER":   (0x038E, "Who is credited for the current hit: 0 or 1, negative for nobody."),
"COMTYP":  (0x038F, "Type occupying each comet slot: 0 = dwarf, $80 = comet. 8 slots."),
"COMSTART": (0x0397, "Where to start searching for a free comet slot, one per ship."),
"PROBCOMET": (0x0399, "Probability that a new object starts as a comet rather than a dwarf, one per ship."),
"DWFRMP":  (0x039B, "Dwarf ramping speed, one per ship."),
"SCSHSP":  (0x039D, "Saucer shooting speed; $80 means fast. One per ship."),
"XINCROT": (0x039F, "Scratch: X velocity after rotation."),
"YINCROT": (0x03A0, "Scratch: Y velocity after rotation."),
"XPOSSAVE": (0x03A1, "Scratch: saved X position."),
"YPOSSAVE": (0x03A2, "Scratch: saved Y position."),
"SHHIGH":  (0x03A3, "Show the high score table when non-zero."),
"FREXPLOSION": (0x03A4, "Explosion sound request."),
"MXRTIMER": (0x03A5, "Value RTIMER is reloaded with, one per ship."),
"NWCACH":  (0x03A7, "Heading change for a newly launched planet or comet, one per ship."),
"NWCSPD":  (0x03A9, "Speed for a newly launched comet, one per ship."),
"FCACH":   (0x03AB, "Heading change for the first comet of a wave, one per ship."),
"FCSPD":   (0x03AD, "Speed for the first comet of a wave, one per ship."),
"WAVE":    (0x03AF, "Wave number, used to scale bonus points."),
"GTIME":   (0x03B0, "Game time accumulated from the 4 ms interrupt, 4 bytes."),
"BCOMSTART": (0x03B4, "Rolling comet-slot search cursor, incremented as comets are launched; one per ship. Atari's source leaves it uncommented."),
"NCOMET":  (0x03B6, "Number of comets currently active."),
"COMTIMER": (0x03B7, "How much longer comets may stay active, for the rush at the end of a wave."),
"COMLIMIT": (0x03B8, "Ceiling on how many comets may be active at once."),
"LNGTIMER": (0x03B9, "Long timer, 2 bytes; once negative, saucers come out even with rocks on screen and shoot fast and often."),
"WHOSHOT": (0x03BB, "Who shot this ship: 0 = the opponent, $FF = the computer. One per ship."),
"NENTCOMETS": (0x03BD, "Number of comets to send in at the end of the wave."),
"NENTDWARF": (0x03BE, "Number of dwarfs to send in at the end of the wave."),
"ETARGET": (0x03BF, "Which ship each saucer is hunting; -1 means inactive. 2 saucers."),
"CTARGET": (0x03C1, "Which object each comet is hunting, 8 comets."),
"KTARGET": (0x03C9, "Which object each killer mine is hunting, 6 mines."),
"SPARKTIME": (0x03CF, "Countdown for the spark arcing between the paired ships; MXSPKTIME ($60) is the maximum and $80, being negative, means no spark."),
"IANGLE":  (0x03D0, "Buffered copy of each ship's angle."),
"LMONHITS": (0x03D2, "Monsters this player has killed, low byte, one per ship."),
"UMONHITS": (0x03D4, "Monsters this player has killed, high byte, one per ship."),
"ASTERS":  (0x03D6, "Rock rotation states, 8 rocks."),
"HSCFLG":  (0x03DE, "Set while initials are being entered, so the sound routine can tell."),
"RODSTATUS": (0x03DF, "Positive when the connecting rod needs drawing or redrawing."),
"SAVBOT":  (0x03E0, COLLIDES + "LASTGAM, the previous game-select reading, used to debounce the select button. SAVBOT is the marker for the start of the RAM that must be preserved."),
"PL0SCFLAG": (0x03E1, "Negative when player 0's score has changed; with a V character it means the life count changed."),
"PL1SCFLAG": (0x03E2, "Negative when player 1's score has changed."),
"CMBSCFLAG": (0x03E3, "Negative when the combined score has changed."),
"UPDOWN":  (0x03E4, "Negative to draw vectors and messages upside down, for the cocktail cabinet's second player."),
"SECOND":  (0x03E5, "One-second tick counter."),
"FLASHCOL": (0x03E6, "Colour used for the flashing display elements."),
"ENTER":   (0x03E7, "Entry-effect timers, 2 bytes."),
"SFREQ":   (0x03E9, "Output frequency of the background hum."),
"SPFLG":   (0x03EA, "Flag for special initials, encoded the same way as UPDFLG."),
"FLSFLG":  (0x03EB, "Flash the initials just entered, 2 bytes."),
"SAUCIX":  (0x03ED, "Saucer picture index, advanced modulo 4 every fourth frame by MoveSaucerPicColor."),
"STRTLOK": (0x03EE, "Start-button lockout: 0 = game in progress, $80 = no starts allowed, $40 = select was pushed and starts are allowed."),
"EXPDEC":  (0x03EF, "Explosion selection, 2 bytes: negative shows the full explosion, positive shows only the flying pieces."),
"SUPRSAC": (0x03F1, "Super saucer flag; $80 means super."),
"SUPRTIM": (0x03F2, "Super saucer shot timer."),
"SUPRDIS": (0x03F3, "Super saucer distance."),
"LASTG":   (0x03F4, "Last game played flag."),
"NEXTEX":  (0x03F5, "Fanfare explosion counter."),
"SPECEX":  (0x03F6, "Special fanfare flag."),
"INTEN":   (0x03F7, "Intensity pulse byte: the top 4 bits of FRAME held in the low nibble."),
"MODNUM":  (0x03F8, "Picture modulo counter; waves flagged $80 cycle it to vary the rock pictures."),
"DIFSW":   (0x03F9, "Difficulty switch reading, kept for the self-test display."),

# ----------------------------------------------------------- hardware, inputs
"HALT":    (0x0800, "In0. D7 3 kHz clock, D6 AVG HALT, D5 diagnostic step, D4 self-test (0 = on), D3 slam, D2-D0 coin sense."),
"HYPSW":   (0x0900, "D7 shield/hyperspace, D6 fire. One switch pair per address through $0907."),
"ROTL":    (0x0902, "D7 rotate left, D6 rotate right."),
"STRT1":   (0x0904, "D7 thrust, D6 one-player start."),
"OPTNA1":  (0x0905, "D6 sell games/players option (SELLGAMES)."),
"GAMSEL":  (0x0906, "D7 game select, D6 two-coin-minimum option (TWOCMN)."),
"CABERE":  (0x0907, "D7 cabinet type (COCKBIT): 1 = cocktail, 0 = upright. AS2DEC.MAC's equate comment says the opposite, but the code settles it - $690C LDX CABERE / BMI, commented 'COCKTAIL?????' / 'YEP...NO ADITIONAL FLIP NEEDED', so minus is the cocktail. D6 caberet select."),
"EAIN":    (0x0A00, "EAROM data read."),

# ---------------------------------------------------------- hardware, outputs
"OUT1":    (0x0C00, "Output latch: D7 Y invert, D6 X invert, D5 start lamp (0 = on), D4 select lamp, D3 coin lockout (1 = no coins), D2-D0 left/centre/right coin counters."),
"GOADD":   (0x0C80, "Write restarts the AVG on the display list at $2000."),
"WTCHDG":  (0x0D00, "Write kicks the watchdog."),
"STOPAD":  (0x0D80, "Write holds the AVG in reset."),
"INTACK":  (0x0E00, "Write acknowledges the 4 ms IRQ."),
"EACTL":   (0x0E80, "EAROM control latch: D0 clock (EACK), D1 C2, D2 C1 inverted, D3 chip enable. C1,C2 = 0,0 read; 1,0 write; 1,1 erase."),
"EADAL":   (0x0F00, "EAROM address and data latch, $0F00-$0F3F."),
"POKEY":   (0x1000, "POKEY 1: sound channels plus the option-switch and pot inputs."),
"POKEY2":  (0x1400, "POKEY 2: sound channels plus the coin-option switches."),

# ------------------------------------------------------------------ vector RAM
"VECMEM":  (0x2000, "Base of the 2K vector RAM; the AVG fetches its display list from here."),
"VROCK1":  (0x2290, "Rock 1: 2-byte JMPL to the chosen rock picture in vector ROM."),
"CVR11":   (0x2292, "Rock 1's first COLOR instruction plus RTSL, 4 bytes, patched each frame."),
"CVR12":   (0x2296, "Rock 1's second COLOR instruction plus RTSL."),
"CVR13":   (0x229A, "Rock 1's third COLOR instruction plus RTSL."),
"VROCK2":  (0x229E, "Rock 2: 2-byte JMPL to the chosen rock picture."),
"CVR21":   (0x22A0, "Rock 2's first COLOR instruction plus RTSL."),
"CVR22":   (0x22A4, "Rock 2's second COLOR instruction plus RTSL."),
"CVR23":   (0x22A8, "Rock 2's third COLOR instruction plus RTSL."),
"VROCK3":  (0x22AC, "Rock 3: 2-byte JMPL to the pyramid picture."),
"PYR11":   (0x22AE, "Pyramid's first COLOR instruction plus RTSL."),
"PYR12":   (0x22B2, "Pyramid's second COLOR instruction plus RTSL."),
"PYR13":   (0x22B6, "Pyramid's third COLOR instruction plus RTSL."),
"VROCK4":  (0x22BA, "Rock 4: 2-byte JMPL, originally the cube. Rocks 4 to 8 reuse the colour instructions above."),
"VROCK5":  (0x22BC, "Rock 5: 2-byte JMPL to its picture."),
"VROCK6":  (0x22BE, "Rock 6: 2-byte JMPL to its picture."),
"VROCK7":  (0x22C0, "Rock 7: 2-byte JMPL to its picture."),
"VROCK8":  (0x22C2, "Rock 8: 2-byte JMPL to its picture."),
"SAU11":   (0x22C4, "Saucer's first COLOR instruction plus RTSL, 4 bytes, patched each frame."),
"SAU12":   (0x22C8, "Saucer's second COLOR instruction plus RTSL."),
"SAU13":   (0x22CC, "Saucer's third COLOR instruction plus RTSL."),
"SPARKB":  (0x22D0, "Spark buffer: $20 bytes of vector code rebuilt each frame for the arc between the paired ships."),
"PL0SET":  (0x2300, "Player 0's score display-list header, 10 bytes."),
"PL1SET":  (0x230A, "Player 1's score display-list header, 10 bytes."),
"CMBSET":  (0x2314, "Combined-score display-list header."),
"CMSBSE":  (0x2342, "CMSBSET: the inverted combined-score header, for the cocktail cabinet's second player."),
"PL0ARE":  (0x2380, "PL0AREA: player 0's score digits. HSAREA immediately precedes it, which is the one critical pairing in vector RAM."),
"PL1ARE":  (0x23C0, "PL1AREA: player 1's score digits."),
"SH0XPCOORD": (0x2700, "Ship 0's explosion-piece coordinates, 4 bytes per piece (Y low, Y high, X low, X high) for 6 pieces."),
"SH1XPCOORD": (0x2718, "Ship 1's explosion-piece coordinates, same layout."),
"CMSBAR":  (0x2736, "CMSBAREA: the inverted combined-score digits."),
"CMBARE":  (0x2780, "CMBAREA: the combined-score digits."),

# ------------------------------------------------------------------ vector ROM
"CKUM4":   (0x2800, COLLIDES + "SHIPS, the 34-entry ship-picture pointer table; this alias holds the low bytes. CKUM4 is a checksum byte the linker placed elsewhere."),
"ROCKA":   (0x2801, COLLIDES + "SHIPS+1, the high bytes of the same table. Shpdisplays reads the pair into VGLIST with LDA CKUM4,Y / LDA ROCKA,Y."),
"ROCKSA":  (0x2811, COLLIDES + "unreferenced. ROCKSA and ROCPIC belong to a relocatable CSECT the linker placed elsewhere, so this address is an artifact of the ASECT walk."),
}


def lookup(name, addr):
    """(description, collides) for an alias, or (None, False) if undocumented.
    Warns on stderr when the recovered address is not the one documented."""
    rec = DOCS.get(name)
    if rec is None:
        return None, False
    want, text = rec
    if want != addr:
        import sys
        sys.stderr.write("var_docs: %s documented at $%04X but recovered at $%04X\n"
                         % (name, want, addr))
    if text.startswith(COLLIDES):
        return text[len(COLLIDES):], True
    return text, False
