# generated by disasm/emit_shapes.py - Space Duel vector object names
VEC_NAMES = {
    0x2844: 'SHPA0',  # ship picture type A, 23+4 records, refs=0
    0x287A: 'SHPA1',  # ship picture type A, 23+4 records, refs=0
    0x28B0: 'SHPA2',  # ship picture type A, 23+4 records, refs=1
    0x2900: 'SHPA3',  # ship picture type A, 23+4 records, refs=0
    0x2936: 'SHPA4',  # ship picture type A, 23+4 records, refs=0
    0x296C: 'SHPA5',  # ship picture type A, 23+4 records, refs=0
    0x29A2: 'SHPA6',  # ship picture type A, 23+4 records, refs=0
    0x2A00: 'SHPA7',  # ship picture type A, 23+4 records, refs=6
    0x2A36: 'SHPA8',  # ship picture type A, 23+4 records, refs=2
    0x2A6C: 'SHPA9',  # ship picture type A, 23+4 records, refs=1
    0x2AA2: 'SHPA10',  # ship picture type A, 23+4 records, refs=1
    0x2B00: 'SHPA11',  # ship picture type A, 23+4 records, refs=1
    0x2B36: 'SHPA12',  # ship picture type A, 23+4 records, refs=0
    0x2B6C: 'SHPA13',  # ship picture type A, 23+4 records, refs=0
    0x2BA2: 'SHPA14',  # ship picture type A, 23+4 records, refs=1
    0x2C00: 'SHPA15',  # ship picture type A, 23+4 records, refs=4
    0x2C36: 'SHPA16',  # ship picture type A, 23+4 records, refs=1
    0x2C6C: 'SHPB0',  # ship picture type B, 21+4 records, refs=0
    0x2C9E: 'SHPB1',  # ship picture type B, 21+4 records, refs=0
    0x2D00: 'SHPB2',  # ship picture type B, 21+4 records, refs=0
    0x2D32: 'SHPB3',  # ship picture type B, 21+4 records, refs=0
    0x2D64: 'SHPB4',  # ship picture type B, 21+4 records, refs=0
    0x2D96: 'SHPB5',  # ship picture type B, 21+4 records, refs=0
    0x2DC8: 'SHPB6',  # ship picture type B, 21+4 records, refs=2
    0x2E00: 'SHPB7',  # ship picture type B, 21+4 records, refs=2
    0x2E32: 'SHPB8',  # ship picture type B, 21+4 records, refs=0
    0x2E64: 'SHPB9',  # ship picture type B, 21+4 records, refs=0
    0x2E96: 'SHPB10',  # ship picture type B, 21+4 records, refs=0
    0x2EC8: 'SHPB11',  # ship picture type B, 21+4 records, refs=0
    0x2F00: 'SHPB12',  # ship picture type B, 21+4 records, refs=0
    0x2F32: 'SHPB13',  # ship picture type B, 21+4 records, refs=2
    0x2F64: 'SHPB14',  # ship picture type B, 21+4 records, refs=0
    0x2F96: 'SHPB15',  # ship picture type B, 21+4 records, refs=0
    0x2FC8: 'SHPB16',  # ship picture type B, 21+4 records, refs=0
    0x3000: 'BOXES',  # vec=9 refs=7
    0x3028: 'BOXCB',  # vec=7 refs=0
    0x3048: 'BOX1?',  # vec=4 refs=0
    0x305A: 'BOX2?',  # vec=6 refs=0
    0x3070: 'BOX3?',  # vec=6 refs=0
    0x3086: 'BOX4?',  # vec=6 refs=0
    0x309C: 'LIVEPAR',  # vec=1 refs=0
    0x30A4: 'LIVUDPAR',  # vec=1 refs=0
    0x30AC: 'LLIVESHIP?',  # vec=0 refs=0
    0x30AE: 'SHAPE_30AE',  # vec=0 refs=0
    0x30B4: 'CHAR.A?',  # vec=0 refs=2
    0x30BC: 'QHEADER',  # vec=5 refs=0
    0x30DC: 'CHR_A',  # vec=7 refs=4
    0x30EC: 'CHR_B',  # vec=27 refs=1
    0x312A: 'CHR_G',  # vec=16 refs=2
    0x3150: 'CHR_J',  # vec=8 refs=7
    0x3164: 'CHR_L',  # vec=12 refs=2
    0x3184: 'CHR_P',  # vec=28 refs=1
    0x31C8: 'CHR_V',  # vec=16 refs=2
    0x31F0: 'CHR_Z',  # vec=11 refs=1
    0x320C: 'CHR_3',  # vec=7 refs=11
    0x321C: 'CHR_4',  # vec=10 refs=7
    0x3234: 'CHR_7',  # vec=4 refs=1
    0x323E: 'CHR_8',  # vec=4 refs=4
    0x3298: 'UCHR.B?',  # vec=18 refs=3
    0x32EA: 'CHRF_A',  # vec=7 refs=2
    0x32FA: 'CHRF_B',  # vec=27 refs=2
    0x3338: 'CHRF_G',  # vec=16 refs=2
    0x335E: 'CHRF_J',  # vec=8 refs=1
    0x3372: 'CHRF_L',  # vec=12 refs=3
    0x3392: 'CHRF_P',  # vec=28 refs=1
    0x33D6: 'CHRF_V',  # vec=16 refs=1
    0x33FE: 'CHRF_Z',  # vec=11 refs=3
    0x341A: 'CHRF_3',  # vec=7 refs=2
    0x342A: 'CHRF_4',  # vec=10 refs=1
    0x3442: 'CHRF_7',  # vec=4 refs=1
    0x344C: 'CHRF_8',  # vec=5 refs=1
    0x34A8: 'CLPAT',  # vec=6 refs=1
    0x34CC: 'CL73',  # vec=3 refs=0
    0x34DC: 'VLINE',  # vec=1 refs=0
    0x34E4: 'HLINE',  # vec=1 refs=0
    0x34EC: 'QTST6',  # vec=8 refs=0
    0x3520: 'LONE?',  # vec=0 refs=4
    0x3528: 'WNDSE',  # vec=2 refs=0
    0x3536: 'RHTSHP',  # vec=23 refs=3
    0x3580: 'LFTSHP',  # vec=21 refs=3
    0x35B4: 'FIGP?',  # vec=24 refs=0
    0x3606: 'EXP14?',  # vec=23 refs=1
    0x3640: 'EXP12?',  # vec=38 refs=3
    0x36AE: 'EXP10?',  # vec=20 refs=1
    0x36E6: 'EXP15?',  # vec=20 refs=1
    0x3712: 'EXP13?',  # vec=20 refs=1
    0x374A: 'EXP11?',  # vec=20 refs=1
    0x378A: 'EXP9?',  # vec=20 refs=1
    0x37C8: 'SHAPE_37C8',  # vec=20 refs=1
    0x3808: 'SHAPE_3808',  # vec=20 refs=1
    0x3848: 'PENT01',  # vec=15 refs=1
    0x3880: 'PENT11',  # vec=12 refs=1
    0x38B0: 'PENT21',  # vec=12 refs=1
    0x38E0: 'PENT31',  # vec=12 refs=1
    0x3910: 'PLN01',  # vec=5 refs=1
    0x3926: 'PLN11',  # vec=8 refs=1
    0x394A: 'PLN21',  # vec=5 refs=1
    0x395E: 'PLN31',  # vec=8 refs=1
    0x3982: 'CUBNM',  # vec=12 refs=0
    0x39AC: 'CUBE01',  # vec=11 refs=1
    0x39D2: 'CUBE11',  # vec=11 refs=1
    0x39EA: 'CUBE21',  # vec=11 refs=1
    0x3A02: 'CUBE31',  # vec=12 refs=9
    0x3A2C: 'PYRM01',  # vec=10 refs=2
    0x3A52: 'PYRM11',  # vec=10 refs=1
    0x3A80: 'PYRM21',  # vec=10 refs=2
    0x3AB4: 'PYRM31',  # vec=10 refs=2
    0x3AE6: 'ROCK01',  # vec=13 refs=2
    0x3B1E: 'ROCK02',  # vec=17 refs=1
    0x3B6E: 'ROCK12',  # vec=17 refs=2
    0x3BBA: 'ROCK22',  # vec=17 refs=1
    0x3C0A: 'ROCK32',  # vec=13 refs=1
    0x3C3E: 'STAR11',  # vec=9 refs=2
    0x3C64: 'STAR21',  # vec=9 refs=1
    0x3C8C: 'STAR31',  # vec=9 refs=1
    0x3CB2: 'HEXA01',  # vec=14 refs=1
    0x3CE0: 'HEXA11',  # vec=14 refs=1
    0x3D0E: 'HEXA21',  # vec=14 refs=1
    0x3D3E: 'HEXA31',  # vec=14 refs=1
    0x3D6C: 'COMET',  # vec=21 refs=0
    0x3DC2: 'DWARF',  # vec=11 refs=0
    0x3DDE: 'SAUC0',  # vec=9 refs=1
    0x3DF8: 'SAUC1',  # vec=9 refs=1
    0x3E12: 'SAUC2',  # vec=10 refs=1
    0x3E2C: 'SAUC3',  # vec=10 refs=1
    0x3E46: 'SAUCRC',  # vec=10 refs=0
    0x3E68: 'MINE',  # vec=12 refs=0
    0x3E84: 'SHOT',  # vec=4 refs=0
    0x3E90: 'PLTLIV',  # vec=2 refs=0
    0x3EA0: 'SHIELD',  # vec=10 refs=0
    0x3EC2: 'CNTSCL',  # vec=0 refs=4
    0x3EC8: 'ASTMG',  # vec=20 refs=0
}
