"""gen_display_data.py - generate c_src/display_data.c + display_data.h.

Extracts the const data tables the display-builder module (display.c)
needs from the 64K image (disasm/build/spacduel_64k.bin, built by
disasm/gen_from_roms.py); never hand-transcribed (CONVENTIONS rule 1c).
Each blob keeps its ROM base address in its name; display.c indexes them
as dsp_rom_XXXX[cpu_addr - 0xXXXX] so the 6502's indexed reads translate
one-for-one, including the code-as-data read at $50C4,Y and the $5F46
branch operand the size-scale table starts on.

Run from anywhere:  py c_src/tools/gen_display_data.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

# (name-base, CPU address, length, provenance comment)
REGIONS = [
    (0x4F1A, 0x02, "Updowtable - UPDOWN value per player for cocktail flip"),
    (0x50A8, 0x2D, "InitializeScoreHeadings_100/110/115/120/125/130 tables, "
                   "ScoreColorBasedAbove code bytes (LDA $50C4,Y reads them "
                   "as data), Scrclr score colors"),
    (0x5F46, 0x22, "Pictur rock scale table (starts on the $5F45 BNE's "
                   "operand byte), Pictur_110, WhiteSaucers shot colors "
                   "(base $5F27,X), Cubltr attract letter codes"),
    (0x5FFE, 0x04, "PositionsTables + MessagePositions (high score screen)"),
    (0x6152, 0x0D, "Scores_110 message numbers, FifthValueUpdateCheck "
                   "high-score-table offsets, Hscend"),
    (0x6257, 0x02, "Shpcor - SH0XPCOORD offset per ship (base $6236,X)"),
    (0x63F0, 0x0E, "Spark2_110 spoke phase offsets; ShipAddressOffsets, "
                   "WhereFirstByteBlank, CountWholeShipVectors, "
                   "CountShipWithThrust, Shpd4table (all base $63D3+..,X "
                   "with X = $21/$22)"),
    (0x6CB5, 0x18, "ChangeDirection + HoldsSign2Byte - ship explosion piece "
                   "velocity/sign tables"),
    (0x6E5C, 0x89, "explosion picture JSRL words ($6E5C normal / $6E6C "
                   "special), rock vector-RAM slot addresses ($6E7D), RSOURC "
                   "32-word JMPL table ($6E8D), comet/dwarf JSRL words "
                   "($6ECD), picture offsets ($6EDD)"),
    (0x764E, 0x08, "high-score-screen ship picture JSRL words "
                   "(MSB $764E,Y / LSB $7652,Y)"),
]


def main():
    img = paths.load_image64k()

    prov = ("GENERATED by c_src/tools/gen_display_data.py\n"
            " * from the 64K image (disasm/build/spacduel_64k.bin)")

    hdr = ["/* display_data.h - %s" % prov,
           " * ROM data tables for the display-builder module (display.c).",
           " * dsp_rom_XXXX[cpu_addr - 0xXXXX] mirrors the 6502's indexed",
           " * reads. Do not edit - regenerate. */",
           "#ifndef DISPLAY_DATA_H",
           "#define DISPLAY_DATA_H",
           "",
           "#include <stdint.h>",
           ""]
    src = ["/* display_data.c - %s" % prov,
           " * Do not edit - regenerate. */",
           '#include "display_data.h"',
           ""]
    for base, size, what in REGIONS:
        data = img[base:base + size]
        hdr.append("/* $%04X-$%04X: %s */" % (base, base + size - 1, what))
        hdr.append("extern const uint8_t dsp_rom_%04X[0x%02X];" % (base, size))
        hdr.append("")
        src.append("/* $%04X: %s */" % (base, what))
        src.append("const uint8_t dsp_rom_%04X[0x%02X] = {" % (base, size))
        for off in range(0, size, 12):
            row = ",".join("0x%02X" % b for b in data[off:off + 12])
            src.append("    /* %04X */ %s," % (base + off, row))
        src.append("};")
        src.append("")
    hdr.append("#endif /* DISPLAY_DATA_H */")

    with open(os.path.join(CSRC, "display_data.h"), "w", newline="\n") as f:
        f.write("\n".join(hdr) + "\n")
    with open(os.path.join(CSRC, "display_data.c"), "w", newline="\n") as f:
        f.write("\n".join(src) + "\n")
    total = sum(size for _, size, _ in REGIONS)
    print("wrote display_data.c / display_data.h (%d regions, %d bytes)"
          % (len(REGIONS), total))


if __name__ == "__main__":
    main()
