#!/usr/bin/env python3
"""Generate sd_state_defs.h (RAM symbol aliases) from spaceduel_defines.asm.

For every .alias whose address is in $0000-$03FF (the 1 KB of CPU RAM) emit:
    #define A_NAME  0xADDR            (the address, for indexed access)
    #define NAME    (g.ram[A_NAME])   (the cell, as an lvalue)
Vector RAM aliases ($2000-$27FF) get A_ constants only (offsets into g.vram
are A_NAME - 0x2000; use VRAM(A_NAME + i)).
Hardware/ROM aliases are emitted as A_ constants for reference.
Rerun after editing spaceduel_defines.asm:  py c_src/tools/gen_state.py
"""
import re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

SRC = paths.DEFINES
OUT = os.path.join(CSRC, "sd_state_defs.h")

aliases = []
for line in open(SRC, encoding="utf-8"):
    m = re.match(r"\.alias\s+(\w+)\s+\$([0-9A-Fa-f]+)\s*(?:;(.*))?", line.strip())
    if m:
        name, addr, cmt = m.group(1), int(m.group(2), 16), (m.group(3) or "").strip()
        aliases.append((name, addr, cmt))

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    w = f.write
    w("/* sd_state_defs.h - GENERATED by c_src/tools/gen_state.py from\n"
      " * ../disasm/spaceduel_defines.asm - do not edit by hand.\n"
      " * A_NAME = CPU address; NAME = the RAM cell as an lvalue. */\n\n")
    w("#ifndef SD_STATE_DEFS_H\n#define SD_STATE_DEFS_H\n\n")
    section = None
    for name, addr, cmt in aliases:
        if addr < 0x400:
            sec = "ram"
        elif 0x2000 <= addr < 0x2800:
            sec = "vram"
        elif 0x2800 <= addr:
            sec = "rom"
        else:
            sec = "hw"
        if sec != section:
            w("\n/* ---- %s ---- */\n" % {
                "ram": "CPU RAM $0000-$03FF (zp + stack + game RAM)",
                "vram": "vector RAM $2000-$27FF (offsets: A_NAME - 0x2000)",
                "rom": "vector/program ROM reference addresses",
                "hw": "hardware registers (reference only - go through sd_hw_*)",
            }[sec])
            section = sec
        c = ("  /* %s */" % cmt) if cmt else ""
        w("#define A_%-12s 0x%04X%s\n" % (name, addr, c))
        if sec == "ram":
            w("#define %-14s (g.ram[A_%s])\n" % (name, name))
    w("\n#endif /* SD_STATE_DEFS_H */\n")

print("wrote %s (%d aliases)" % (os.path.normpath(OUT), len(aliases)))
