"""gen_score_data.py - generate c_src/score_data.c + score_data.h.

Extracts the const data tables the scoring/high-score module (score.c)
needs from the 64K image (disasm/build/spacduel_64k.bin, built by
disasm/gen_from_roms.py); never hand-transcribed (CONVENTIONS rule 1c).
Each blob keeps its ROM base address in its name; score.c indexes them
as score_rom_XXXX[cpu_addr - 0xXXXX] so the 6502's indexed reads
translate one-for-one, including the overlapping/aliased views the ROM
exploits (e.g. Picadh's 3rd entry silently reading into Mesg2, and the
Creddis byte blob being reread at three different offsets for unrelated
purposes).

Run from anywhere:  py c_src/tools/gen_score_data.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

# (CPU address, length, provenance comment)
REGIONS = [
    (0x6156, 0x09, "FifthValueUpdateCheck (high-score-table start offsets "
                   "per game type, 5 bytes) + Hscend (initials-shift end "
                   "offsets per game type, 4 bytes) - UpdateHighScoreTable"),
    (0x761E, 0x3F, "Display4Names_100/110/120/130/140/150/160/170/180/185 "
                   "position/message tables, Picadh (box pic JSRL hi, 3 "
                   "bytes - 4th read of this table lands on Mesg2[0], both "
                   "$A8, a genuine ROM overlap), Mesg2 (box pic JSRL lo), "
                   "Creddis (credit-display message/JSRL byte blob, reread "
                   "at offsets +1/+5/+9/+12 for unrelated tables)"),
]


def main():
    img = paths.load_image64k()

    prov = ("GENERATED by c_src/tools/gen_score_data.py\n"
            " * from the 64K image (disasm/build/spacduel_64k.bin)")

    hdr = ["/* score_data.h - %s" % prov,
           " * ROM data tables for the scoring/high-score module (score.c).",
           " * score_rom_XXXX[cpu_addr - 0xXXXX] mirrors the 6502's indexed",
           " * reads. Do not edit - regenerate. */",
           "#ifndef SCORE_DATA_H",
           "#define SCORE_DATA_H",
           "",
           "#include <stdint.h>",
           ""]
    src = ["/* score_data.c - %s" % prov,
           " * Do not edit - regenerate. */",
           '#include "score_data.h"',
           ""]
    total = 0
    for base, size, what in REGIONS:
        data = img[base:base + size]
        hdr.append("/* $%04X-$%04X: %s */" % (base, base + size - 1, what))
        hdr.append("extern const uint8_t score_rom_%04X[0x%02X];" % (base, size))
        hdr.append("")
        src.append("/* $%04X: %s */" % (base, what))
        src.append("const uint8_t score_rom_%04X[0x%02X] = {" % (base, size))
        for off in range(0, size, 12):
            row = ",".join("0x%02X" % b for b in data[off:off + 12])
            src.append("    /* %04X */ %s," % (base + off, row))
        src.append("};")
        src.append("")
        total += size
    hdr.append("#endif /* SCORE_DATA_H */")

    with open(os.path.join(CSRC, "score_data.h"), "w", newline="\n") as f:
        f.write("\n".join(hdr) + "\n")
    with open(os.path.join(CSRC, "score_data.c"), "w", newline="\n") as f:
        f.write("\n".join(src) + "\n")
    print("wrote score_data.c / score_data.h (%d regions, %d bytes)"
          % (len(REGIONS), total))


if __name__ == "__main__":
    main()
