"""gen_msgs_data.py - generate c_src/msgs_data.c from the ROM image.

Extracts the const tables of the AS2MSG message module from the 64K
image (disasm/build/spacduel_64k.bin, built by disasm/gen_from_roms.py);
never hand-transcribed (CONVENTIONS rule 1c).  The tables:

    msgs_offset_rom[28]     ROM $7744-$775F  Offset - language X-position
                            deltas, 7 rows of 4 (row = caller's X, col =
                            language 0-3), used by AuxRoutineAddOffset.
    msgs_text_rom[0x502]    ROM $7803-$7D04  LanguageTablePointersSee
                            (8 little-endian pointers: 4 languages x 2
                            message banks), the per-bank message-offset
                            tables, and all packed 3-chars-per-2-bytes
                            message text, addressed by VectorMessage6
                            through the WHITE/EACE zero-page pointer.

Every extracted byte is cross-checked against the .byte lines of the
annotated listing disasm/spaceduel_program_rom.asm (which is
itself byte-verified against the ROM set); any disagreement aborts.

Run from anywhere:  py c_src/tools/gen_msgs_data.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

TABLES = [
    ("msgs_offset_rom", 0x7744, 0x001C,
     "Offset ($7744): AuxRoutineAddOffset language X deltas, 7 rows x 4 langs"),
    ("msgs_text_rom", 0x7803, 0x0502,
     "LanguageTablePointersSee ($7803) + per-bank offset tables + packed text"),
]


def load_64k():
    return paths.load_image64k()


def listing_bytes():
    """Parse every 'Lxxxx:  .byte ...' line into {addr: value}."""
    path = paths.PROGRAM_ROM
    rx = re.compile(r"^L([0-9A-F]{4}):\s+\.byte\s+(.+?)\s*(?:;.*)?$")
    out = {}
    with open(path, "r") as f:
        for line in f:
            m = rx.match(line)
            if not m:
                continue
            addr = int(m.group(1), 16)
            for i, tok in enumerate(m.group(2).split(",")):
                tok = tok.strip()
                if tok.startswith("$"):
                    out[addr + i] = int(tok[1:], 16)
    return out


def cross_check(img, lst):
    total = 0
    for name, base, size, _ in TABLES:
        misses = 0
        for a in range(base, base + size):
            if a not in lst:
                misses += 1          # listing byte inside code span etc.
                continue
            if lst[a] != img[a]:
                raise SystemExit("%s: $%04X listing=$%02X bin=$%02X"
                                 % (name, a, lst[a], img[a]))
            total += 1
        if misses:
            raise SystemExit("%s: %d bytes of $%04X-$%04X not .byte lines "
                             "in the listing" % (name, misses, base,
                                                 base + size - 1))
    print("cross-check vs listing .byte lines: %d/%d bytes match"
          % (total, sum(t[2] for t in TABLES)))


def emit(img):
    lines = [
        "/* msgs_data.c - Space Duel AS2MSG const tables ($7744, $7803-$7D04).",
        " * generated by c_src/tools/gen_msgs_data.py from the 64K image",
        " * (disasm/build/spacduel_64k.bin), cross-checked byte-for-byte",
        " * against the listing's .byte lines.",
        " * Do not edit - regenerate. Declarations live in msgs.h. */",
        "#include <stdint.h>",
        "",
    ]
    for name, base, size, desc in TABLES:
        lines.append("/* %s */" % desc)
        lines.append("const uint8_t %s[0x%04X] = {" % (name, size))
        for off in range(0, size, 16):
            row = ",".join("0x%02X" % b
                           for b in img[base + off:base + min(size, off + 16)])
            lines.append("    /* %04X */ %s," % (base + off, row))
        lines.append("};")
        lines.append("")
    with open(os.path.join(CSRC, "msgs_data.c"), "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote msgs_data.c (%s)" %
          ", ".join("%s[%d] @ $%04X" % (n, s, b) for n, b, s, _ in TABLES))


if __name__ == "__main__":
    img = load_64k()
    cross_check(img, listing_bytes())
    emit(img)
