"""gen_vecrom.py - generate c_src/sd_vecrom.c + sd_vecrom.h from the ROM set.

sd_vecrom[0x1800] = the bytes the 6502 (and the AVG, flat-mapped - see
DESIGN.md "JMPL address fold") sees at CPU $2800-$3FFF:

    136006-106  2 KB  CPU $2800-$2FFF  (ship-picture table, NOT AVG data)
    136006-107  4 KB  CPU $3000-$3FFF  (AVG vector ROM: glyphs, shapes)

Verifies each image size and that the concatenation matches the
$2800-$3FFF slice of the 64K image (disasm/build/spacduel_64k.bin, built
by disasm/gen_from_roms.py) byte-for-byte.

Run from anywhere:  py c_src/tools/gen_vecrom.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

ROMS = [("136006.106", 0x2800, 0x0800),
        ("136006.107", 0x3000, 0x1000)]
BASE, SIZE = 0x2800, 0x1800


def load():
    data = bytearray()
    for fn, base, size in ROMS:
        d = paths.rom_bytes(paths.roms_dir(), fn, size)
        if BASE + len(data) != base:
            raise SystemExit("%s: not contiguous at $%04X" % (fn, base))
        data += d
    if len(data) != SIZE:
        raise SystemExit("concatenation is %d bytes, expected %d" % (len(data), SIZE))
    return bytes(data)


def verify_64k(data):
    img = paths.load_image64k()
    ref = img[BASE:BASE + SIZE]
    if ref != data:
        bad = [i for i in range(SIZE) if ref[i] != data[i]]
        raise SystemExit("MISMATCH vs spacduel_64k.bin: %d bytes, first at $%04X"
                         % (len(bad), BASE + bad[0]))
    print("cross-check vs spacduel_64k.bin[$2800:$4000]: %d/%d bytes match"
          % (SIZE, SIZE))


def emit(data):
    prov = ("generated by c_src/tools/gen_vecrom.py from ROMs 136006-106\n"
            " * (2 KB @ $2800) and 136006-107 (4 KB @ $3000); verified\n"
            " * against the 64K image (disasm/build/spacduel_64k.bin).")
    with open(os.path.join(CSRC, "sd_vecrom.h"), "w", newline="\n") as f:
        f.write("/* sd_vecrom.h - Space Duel vector ROM image, CPU $2800-$3FFF.\n"
                " * %s\n"
                " * $2800-$2FFF is the ship-picture table (not AVG data);\n"
                " * $3000-$3FFF is the AVG vector ROM (glyphs at $324A/$3458, shapes).\n"
                " * Do not edit - regenerate. */\n"
                "#ifndef SD_VECROM_H\n"
                "#define SD_VECROM_H\n\n"
                "#include <stdint.h>\n\n"
                "#define SD_VECROM_BASE 0x2800u   /* CPU address of sd_vecrom[0] */\n"
                "#define SD_VECROM_SIZE 0x1800u\n\n"
                "extern const uint8_t sd_vecrom[0x1800];\n\n"
                "#endif /* SD_VECROM_H */\n" % prov)
    lines = ["/* sd_vecrom.c - Space Duel vector ROM image, CPU $2800-$3FFF.",
             " * %s */" % prov,
             '#include "sd_vecrom.h"',
             "",
             "const uint8_t sd_vecrom[0x1800] = {"]
    for off in range(0, SIZE, 16):
        row = ",".join("0x%02X" % b for b in data[off:off + 16])
        lines.append("    /* %04X */ %s," % (BASE + off, row))
    lines.append("};")
    with open(os.path.join(CSRC, "sd_vecrom.c"), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote sd_vecrom.c / sd_vecrom.h (%d bytes, base $%04X)" % (SIZE, BASE))


if __name__ == "__main__":
    d = load()
    verify_64k(d)
    emit(d)
