#!/usr/bin/env python3
"""Generate sd_state_defs.h (RAM symbol aliases) from spaceduel_defines.asm.

Every .alias becomes an address constant:
    #define A_NAME  0xADDR            (for indexed access)
and, when it names a real variable in CPU RAM, also the cell as an lvalue:
    #define NAME    (g.ram[A_NAME])

Which aliases get the lvalue is decided by the defines file's own
";---[ Section ]---" heading, NOT by the address.  Only the VARIABLE
sections yield lvalues.  The "Memory map" section's aliases (ZeroPageRam,
StackRam, GameRam, ...) are region markers, not cells: emitting GameRam as
an lvalue invents a variable at $0200 that Atari never declared.  Inputs,
Outputs, the hardware registers and Vector RAM/ROM are reference-only too -
the port reaches hardware through the sd_hw_* seam, and vector RAM through
VRAM(A_NAME - 0x2000 + i).

(Rule backported from the Gravitar port's tools/gen_state.py, 2026-09-13;
the three variable-section headings are identical in both defines files.
Space Duel's RAM is 1 KB, not Gravitar's 2 KB.)

The output is still grouped by ADDRESS RANGE, the way this file has always
grouped it, so the only thing the rule changed in sd_state_defs.h is the
three region markers losing their lvalue lines.

Rerun after editing spaceduel_defines.asm:  py c_src/tools/gen_state.py
"""
import re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

SRC = paths.DEFINES
OUT = os.path.join(CSRC, "sd_state_defs.h")

RAM_END = 0x0400          # $0000-$03FF is CPU RAM

# The defines file's sections that declare real variables.  Everything else
# is a region marker or a hardware register: address constant only.  These
# three headings are identical in the Gravitar defines file.
VAR_SECTIONS = ("Zero page variables", "Stack page", "Game RAM")

SECTION_RE = re.compile(r"^;-*\[\s*(.*?)\s*\]-*$")
ALIAS_RE   = re.compile(r"\.alias\s+(\w+)\s+\$([0-9A-Fa-f]+)\s*(?:;(.*))?")


def parse(path):
    """[(section, name, addr, comment)] in file order."""
    out, section = [], ""
    for line in open(path, encoding="utf-8"):
        m = SECTION_RE.match(line.strip())
        if m:
            section = m.group(1)
            continue
        m = ALIAS_RE.match(line.strip())
        if m:
            out.append((section, m.group(1), int(m.group(2), 16),
                        (m.group(3) or "").strip()))
    return out


def main():
    aliases = parse(SRC)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        w = f.write
        w("/* sd_state_defs.h - GENERATED by c_src/tools/gen_state.py from\n"
          " * ../disasm/spaceduel_defines.asm - do not edit by hand.\n"
          " *\n"
          " * A_NAME is the CPU address of every alias.  NAME is the RAM cell\n"
          " * as an lvalue, emitted only for the variable sections - a region\n"
          " * marker or a hardware register gets the address and nothing more.\n"
          " * Vector RAM: use VRAM(A_NAME - 0x2000 + i).  Hardware: sd_hw_*. */\n\n")
        w("#ifndef SD_STATE_DEFS_H\n#define SD_STATE_DEFS_H\n\n")
        section, nram = None, 0
        for sec, name, addr, cmt in aliases:
            if addr < 0x400:
                grp = "ram"
            elif 0x2000 <= addr < 0x2800:
                grp = "vram"
            elif 0x2800 <= addr:
                grp = "rom"
            else:
                grp = "hw"
            if grp != section:
                w("\n/* ---- %s ---- */\n" % {
                    "ram": "CPU RAM $0000-$03FF (zp + stack + game RAM)",
                    "vram": "vector RAM $2000-$27FF (offsets: A_NAME - 0x2000)",
                    "rom": "vector/program ROM reference addresses",
                    "hw": "hardware registers (reference only - go through sd_hw_*)",
                }[grp])
                section = grp
            c = ("  /* %s */" % cmt) if cmt else ""
            w("#define A_%-12s 0x%04X%s\n" % (name, addr, c))
            if sec in VAR_SECTIONS and addr < RAM_END:
                w("#define %-14s (g.ram[A_%s])\n" % (name, name))
                nram += 1
        w("\n#endif /* SD_STATE_DEFS_H */\n")

    print("wrote %s (%d aliases, %d of them RAM cells)"
          % (os.path.normpath(OUT), len(aliases), nram))


if __name__ == "__main__":
    main()
