"""gen_sound_data.py - generate c_src/sound_data.c + sound_data.h from the ROM.

sd_sndrom[] = the program-ROM bytes at CPU $703C-$7419, the whole
AS2SAC/AS2POK sound module (code AND data), extracted from the 64K image
(disasm/build/spacduel_64k.bin, built by disasm/gen_from_roms.py).

Why the whole region and not just the tables: the sound driver's indexed reads
are open-ended -

  - LDA $707F,X  ($707A, AlwaysRemainsSameBoth): X = SUPRDIS, lands in the
    Time table at $7083 for the real distances (X >= 4);
  - LDA $70C1,Y  ($7301, Badhab): Y = sound code down to code-15, code max $DF,
    so the channel-map table spans $70C1-$71A0;
  - LDA $719B,Y / $719C,Y / $719D,Y / $729B,Y ... ($7339-$737B): the sound
    scripts are addressed as base + pointer*2 with the ASL carry selecting the
    $729B bank, i.e. one seamless 9-bit space $719B-$739C.

Extracting the contiguous module region makes every one of those reads
byte-exact for any index the ROM can produce, without hand-picking table
boundaries. Cross-checks a handful of known bytes against the annotated
listing values before emitting.

Run from anywhere:  py c_src/tools/gen_sound_data.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

BASE, END = 0x703C, 0x741A          # [BASE, END)
SIZE = END - BASE                   # 0x3DE = 990 bytes

# spot checks: (addr, bytes) straight from the annotated listing
CHECKS = [
    (0x7083, bytes([0x02, 0x02, 0x03, 0x04, 0x04, 0x05, 0x05, 0x06,
                    0x06, 0x07, 0x07, 0x07, 0x08, 0x08])),          # Time
    (0x70C0, bytes([0x90, 0x00, 0x00, 0x01, 0x04])),                # chan map
    (0x71A0, bytes([0x00])),                        # TablesOffsetPointerSounds
    (0x71A1, bytes([0x01, 0x08, 0x02, 0x10, 0x00, 0x00])),          # Pntrs
    (0x72A1, bytes([0x20, 0x01, 0x00, 0x03, 0x80, 0x01, 0x10, 0x06])),  # Pp2f
]
# coins.c inlines this 8-byte table; verify it here too (not emitted)
COIN_CHECK = (0x74CF, bytes([0x7F, 0x02, 0x04, 0x04, 0x05, 0x03, 0x7F, 0x7F]))


def load():
    img = paths.load_image64k()
    for addr, want in CHECKS + [COIN_CHECK]:
        got = img[addr:addr + len(want)]
        if got != want:
            raise SystemExit("check failed at $%04X: got %s want %s"
                             % (addr, got.hex(), want.hex()))
    print("all listing spot-checks passed (incl. NumberUnitCoinsRequired $74CF)")
    return img[BASE:END]


def emit(data):
    prov = ("generated by c_src/tools/gen_sound_data.py from the 64K image\n"
            " * (disasm/build/spacduel_64k.bin) [$703C:$741A]; spot-checked\n"
            " * against the annotated listing.")
    with open(os.path.join(CSRC, "sound_data.h"), "w", newline="\n") as f:
        f.write("/* sound_data.h - Space Duel AS2SAC sound module ROM bytes,"
                " CPU $703C-$7419.\n"
                " * %s\n"
                " * Do not edit - regenerate. */\n"
                "#ifndef SOUND_DATA_H\n"
                "#define SOUND_DATA_H\n\n"
                "#include <stdint.h>\n\n"
                "#define SD_SNDROM_BASE 0x703Cu  /* CPU address of sd_sndrom[0] */\n"
                "#define SD_SNDROM_SIZE 0x%03Xu\n\n"
                "extern const uint8_t sd_sndrom[0x%03X];\n\n"
                "/* read a sound-module ROM byte by CPU address */\n"
                "#define SNDROM(a)  (sd_sndrom[(uint16_t)(a) - SD_SNDROM_BASE])\n\n"
                "#endif /* SOUND_DATA_H */\n" % (prov, SIZE, SIZE))
    lines = ["/* sound_data.c - Space Duel AS2SAC sound module ROM bytes,"
             " CPU $703C-$7419.",
             " * %s */" % prov,
             '#include "sound_data.h"',
             "",
             "const uint8_t sd_sndrom[0x%03X] = {" % SIZE]
    for off in range(0, SIZE, 16):
        row = ",".join("0x%02X" % b for b in data[off:off + 16])
        lines.append("    /* %04X */ %s," % (BASE + off, row))
    lines.append("};")
    with open(os.path.join(CSRC, "sound_data.c"), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote sound_data.c / sound_data.h (%d bytes, base $%04X)"
          % (SIZE, BASE))


if __name__ == "__main__":
    emit(load())
