"""gen_progrom.py - generate c_src/sd_progrom.c + sd_progrom.h from the ROM set.

sd_progrom[0x5000] = the program ROM bytes the 6502 sees at CPU $4000-$8FFF
(the $8000-$8FFF ROM is mirrored up to $FFFF and supplies the vectors, but
the code never reads above $8FFF except through that mirror):

    136006-201  4 KB  CPU $4000-$4FFF
    136006-102  4 KB  CPU $5000-$5FFF
    136006-103  4 KB  CPU $6000-$6FFF
    136006-104  4 KB  CPU $7000-$7FFF
    136006-105  4 KB  CPU $8000-$8FFF

Why the C port carries its own program text as DATA: the self-test
(selftest.c, AS2TST) EOR-checksums every ROM at power-on ($8244
EorCksumRoms) and the signature-analysis mode copies AVG test lists out of
the ROM with an indexed read that can run past its table ($8D85 LDY
$8DC0,X with X = $80|jumpers). Both are reads of the ROM as bytes; the
faithful translation reads the real bytes.

Verifies each image size and that the concatenation matches the
$4000-$8FFF slice of the 64K image (disasm/build/spacduel_64k.bin, built
by disasm/gen_from_roms.py) byte-for-byte.

Run from anywhere:  py c_src/tools/gen_progrom.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))   # project root
CSRC = os.path.normpath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "disasm"))
import paths

ROMS = [("136006.201", 0x4000, 0x1000),
        ("136006.102", 0x5000, 0x1000),
        ("136006.103", 0x6000, 0x1000),
        ("136006.104", 0x7000, 0x1000),
        ("136006.105", 0x8000, 0x1000)]
BASE, SIZE = 0x4000, 0x5000


def load():
    data = bytearray()
    for fn, base, size in ROMS:
        d = paths.rom_bytes(paths.roms_dir(), fn, size)
        if BASE + len(data) != base:
            raise SystemExit("%s: not contiguous at $%04X" % (fn, base))
        data += d
    if len(data) != SIZE:
        raise SystemExit("concatenation is %d bytes, expected %d" % (len(data), SIZE))
    return bytes(data)


def verify_64k(data):
    img = paths.load_image64k()
    ref = img[BASE:BASE + SIZE]
    if ref != data:
        bad = [i for i in range(SIZE) if ref[i] != data[i]]
        raise SystemExit("MISMATCH vs spacduel_64k.bin: %d bytes, first at $%04X"
                         % (len(bad), BASE + bad[0]))
    print("cross-check vs spacduel_64k.bin[$4000:$9000]: %d/%d bytes match"
          % (SIZE, SIZE))
    # the self-test's own acceptance criterion: each 4 KB ROM EORs to its
    # index (the seed X at $825E), the 2 KB vector ROM to $FF - report it
    for i, (fn, base, size) in enumerate(ROMS):
        s = i + 1                       # $3000 is index 0, $4000 index 1 ...
        for b in data[base - BASE:base - BASE + size]:
            s ^= b
        print("  %s @ $%04X: EOR checksum seeded %d -> $%02X%s"
              % (fn, base, i + 1, s, "" if s == 0 else "  (self-test would flag)"))


def emit(data):
    prov = ("generated by c_src/tools/gen_progrom.py from ROMs 136006-201,\n"
            " * -102, -103, -104 and -105 (5 x 4 KB @ $4000-$8FFF); verified\n"
            " * against the 64K image (disasm/build/spacduel_64k.bin).")
    with open(os.path.join(CSRC, "sd_progrom.h"), "w", newline="\n") as f:
        f.write("/* sd_progrom.h - Space Duel program ROM image, CPU $4000-$8FFF.\n"
                " * %s\n"
                " * Carried as DATA for the self-test's ROM checksum loop\n"
                " * ($8244 EorCksumRoms) and the signature-analysis table\n"
                " * copies ($8D85) - see selftest.c. Do not edit - regenerate. */\n"
                "#ifndef SD_PROGROM_H\n"
                "#define SD_PROGROM_H\n\n"
                "#include <stdint.h>\n\n"
                "#define SD_PROGROM_BASE 0x4000u   /* CPU address of sd_progrom[0] */\n"
                "#define SD_PROGROM_SIZE 0x5000u\n\n"
                "extern const uint8_t sd_progrom[0x5000];\n\n"
                "#endif /* SD_PROGROM_H */\n" % prov)
    lines = ["/* sd_progrom.c - Space Duel program ROM image, CPU $4000-$8FFF.",
             " * %s */" % prov,
             '#include "sd_progrom.h"',
             "",
             "const uint8_t sd_progrom[0x5000] = {"]
    for off in range(0, SIZE, 16):
        row = ",".join("0x%02X" % b for b in data[off:off + 16])
        lines.append("    /* %04X */ %s," % (BASE + off, row))
    lines.append("};")
    with open(os.path.join(CSRC, "sd_progrom.c"), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote sd_progrom.c / sd_progrom.h (%d bytes, base $%04X)" % (SIZE, BASE))


if __name__ == "__main__":
    d = load()
    verify_64k(d)
    emit(d)
