/* display_data.h - GENERATED by c_src/tools/gen_display_data.py
 * from the 64K image (disasm/build/spacduel_64k.bin)
 * ROM data tables for the display-builder module (display.c).
 * dsp_rom_XXXX[cpu_addr - 0xXXXX] mirrors the 6502's indexed
 * reads. Do not edit - regenerate. */
#ifndef DISPLAY_DATA_H
#define DISPLAY_DATA_H

#include <stdint.h>

/* $4F1A-$4F1B: Updowtable - UPDOWN value per player for cocktail flip */
extern const uint8_t dsp_rom_4F1A[0x02];

/* $50A8-$50D4: InitializeScoreHeadings_100/110/115/120/125/130 tables, ScoreColorBasedAbove code bytes (LDA $50C4,Y reads them as data), Scrclr score colors */
extern const uint8_t dsp_rom_50A8[0x2D];

/* $5F46-$5F67: Pictur rock scale table (starts on the $5F45 BNE's operand byte), Pictur_110, WhiteSaucers shot colors (base $5F27,X), Cubltr attract letter codes */
extern const uint8_t dsp_rom_5F46[0x22];

/* $5FFE-$6001: PositionsTables + MessagePositions (high score screen) */
extern const uint8_t dsp_rom_5FFE[0x04];

/* $6152-$615E: Scores_110 message numbers, FifthValueUpdateCheck high-score-table offsets, Hscend */
extern const uint8_t dsp_rom_6152[0x0D];

/* $6257-$6258: Shpcor - SH0XPCOORD offset per ship (base $6236,X) */
extern const uint8_t dsp_rom_6257[0x02];

/* $63F0-$63FD: Spark2_110 spoke phase offsets; ShipAddressOffsets, WhereFirstByteBlank, CountWholeShipVectors, CountShipWithThrust, Shpd4table (all base $63D3+..,X with X = $21/$22) */
extern const uint8_t dsp_rom_63F0[0x0E];

/* $6CB5-$6CCC: ChangeDirection + HoldsSign2Byte - ship explosion piece velocity/sign tables */
extern const uint8_t dsp_rom_6CB5[0x18];

/* $6E5C-$6EE4: explosion picture JSRL words ($6E5C normal / $6E6C special), rock vector-RAM slot addresses ($6E7D), RSOURC 32-word JMPL table ($6E8D), comet/dwarf JSRL words ($6ECD), picture offsets ($6EDD) */
extern const uint8_t dsp_rom_6E5C[0x89];

/* $764E-$7655: high-score-screen ship picture JSRL words (MSB $764E,Y / LSB $7652,Y) */
extern const uint8_t dsp_rom_764E[0x08];

#endif /* DISPLAY_DATA_H */
