/* lowones.h - Space Duel C port: per-frame "low ones" service + the trig/
 * multiply math pack (module AST2RT, $6831-$68C9 and $6EE5-$703B).
 *
 * Register protocols are documented above each function in lowones.c and in
 * NOTES_lowones.md; carry/flag protocols are explicit parameters/returns.
 */
#ifndef LOWONES_H
#define LOWONES_H

#include <stdint.h>

/* ---- math pack ($6831-$68C9) ------------------------------------------- */
uint8_t cos_sin_pi2(uint8_t a);        /* CosSinPi2 $6831: A=angle -> A=cos */
uint8_t pi_angle0(uint8_t a);          /* PiAngle0  $6834: A=angle -> A=sin */
uint8_t sin1(uint8_t a);               /* Sin1      $683E: A=0..$7F only    */
uint8_t comp(uint8_t a);               /* Comp      $684D: A -> -A          */
                                       /* Comp1     $6852: bare RTS (none)  */
uint8_t entry_input_exit_absolute(uint8_t a); /* $684B: A -> |A|            */
uint8_t signed_by_signed_mult(uint8_t a);     /* SignedBySignedMult $6853   */
uint8_t output_temp2_temp21(uint8_t a);       /* OutputTemp2Temp21  $686D   */

/* ---- signed arctangent ($67D0-$6830) ----------------------------------- */
/* PartSignedNumberExit $67D0: in x = the X (denominator) difference,
 * y = the Y (numerator) difference, both signed; out A = the angle,
 * 256 units per circle (same units as pi_angle0/cos_sin_pi2).  Clobbers
 * the 6502 X and Y; writes POTGO ($0B) and POKRAN ($0A).  x == y == 0
 * returns $20 (the ROM's degenerate answer).  Divisor $67DC, Divisor2
 * $67EB, L4BitDivide $6805 and Temp21DivisorUnsigned $681F are its
 * internal stages (static in lowones.c; no outside callers). */
uint8_t part_signed_number_exit(uint8_t x, uint8_t y);

/* ---- per-frame star/saucer picture service ($6EE5-$703B) --------------- */
void do_low_ones_every(void);          /* DoLowOnesEvery $6EE5 (falls into  */
void toppic(void);                     /* Toppic $6F6E, which falls into    */
void move_saucer_pic_color(void);      /* MoveSaucerPicColor $6F92)         */
uint8_t l80_random_wave0(uint8_t x, uint8_t y); /* L80RandomWave0 $6FDD     */
uint8_t save_later(uint8_t x);         /* SaveLater $7017: returns Y = x*2  */
uint8_t get_rotation_color_code(uint8_t x);   /* $701F: returns Y = 2       */

/* ---- const tables (lowones_data.c, generated by gen_lowones_data.py) --- */
extern const uint8_t lowones_atan16[0x10];     /* L03   $680F 4-bit arctan  */
extern const uint8_t lowones_sin07[0x41];      /* Sin07 $6D1B               */
extern const uint8_t lowones_nibmul[0x100];    /* $6D5C nibble products     */
extern const uint8_t lowones_stardest[0x10];   /* $6E7D star vgram slots    */
extern const uint8_t lowones_rsourc[0x40];     /* RSOURC $6E8D JMPL words   */
extern const uint8_t lowones_piccode[0x08];    /* $6EDD picture codes       */
extern const uint8_t lowones_mod_m1[0x13];     /* Mod $6FB9, base-1         */
extern const uint8_t lowones_randsel_m1[0x13]; /* $6FCB, base-1             */
extern const uint8_t lowones_colortab[0x0E];   /* ColorTable+Barco2 $7009   */

#endif /* LOWONES_H */
