/* mainline_data.c - Space Duel mainline/boot const tables.
 * generated by c_src/tools/gen_mainline_data.py from the 64K image
 * (disasm/build/spacduel_64k.bin), cross-checked against the
 * listing's .byte lines. Do not edit - regenerate. Declarations
 * in mainline.h. */
#include <stdint.h>

/* TableGameOrder ($43B3): Nxtstep's game-select rotation */
const uint8_t mainline_game_order[0x04] = {
    /* 43B3 */ 0x01,0x03,0x00,0x02,
};

/* EndingValueKillerMine ($6A9B) + $6AA0 overflow byte (X=5 read) */
const uint8_t mainline_evkm[0x06] = {
    /* 6A9B */ 0x70,0x60,0x60,0x50,0x40,0x18,
};

/* Kchend ($6AA0) + $6AA5 overflow byte (X=5 read; $6AA5 is code) */
const uint8_t mainline_kchend[0x06] = {
    /* 6AA0 */ 0x18,0x10,0x10,0x0C,0x08,0xA2,
};

/* Comentable ($6ACF): Inco10's lowest comet slot to scan, per player */
const uint8_t mainline_comentable[0x02] = {
    /* 6ACF */ 0x11,0x15,
};

/* Ttplayr ($6CD5): credits required per game type */
const uint8_t mainline_ttplayr[0x04] = {
    /* 6CD5 */ 0x02,0x01,0x02,0x01,
};

/* $6D0F: NewCometAngleChange(4) + NewCometTopSpeed(4) + FirstCometSTop(4) - SinceCannotGetMust's per-difficulty ramp, indexed by KLMINC */
const uint8_t mainline_comet_ramp[0x0C] = {
    /* 6D0F */ 0x01,0x01,0x02,0x03,0x01,0x02,0x03,0x04,0x02,0x03,0x04,0x05,
};

/* BonusOptionSwitchesAssumed ($7724): bonus-life level per DIP pair */
const uint8_t mainline_bonus_optn[0x04] = {
    /* 7724 */ 0x00,0x08,0x10,0x15,
};

/* Fighters ($7728) + SpaceStation ($772C): Gtoptn difficulty, X=0-7 */
const uint8_t mainline_fighters[0x08] = {
    /* 7728 */ 0x01,0x02,0x02,0x03,0x01,0x01,0x02,0x03,
};

/* Ininitls ($802D): default high-score initials, X=0-$0E */
const uint8_t mainline_ininitls[0x0F] = {
    /* 802D */ 0x00,0x00,0x00,0x19,0x1C,0x1C,0x1D,0x1C,0x0D,0x0E,0x0F,0x1D,0x14,0x17,0x1C,
};
