/* score_data.h - GENERATED by c_src/tools/gen_score_data.py
 * from the 64K image (disasm/build/spacduel_64k.bin)
 * ROM data tables for the scoring/high-score module (score.c).
 * score_rom_XXXX[cpu_addr - 0xXXXX] mirrors the 6502's indexed
 * reads. Do not edit - regenerate. */
#ifndef SCORE_DATA_H
#define SCORE_DATA_H

#include <stdint.h>

/* $6156-$615E: FifthValueUpdateCheck (high-score-table start offsets per game type, 5 bytes) + Hscend (initials-shift end offsets per game type, 4 bytes) - UpdateHighScoreTable */
extern const uint8_t score_rom_6156[0x09];

/* $761E-$765C: Display4Names_100/110/120/130/140/150/160/170/180/185 position/message tables, Picadh (box pic JSRL hi, 3 bytes - 4th read of this table lands on Mesg2[0], both $A8, a genuine ROM overlap), Mesg2 (box pic JSRL lo), Creddis (credit-display message/JSRL byte blob, reread at offsets +1/+5/+9/+12 for unrelated tables) */
extern const uint8_t score_rom_761E[0x3F];

#endif /* SCORE_DATA_H */
