/* sd_progrom.h - Space Duel program ROM image, CPU $4000-$8FFF.
 * generated by c_src/tools/gen_progrom.py from ROMs 136006-201,
 * -102, -103, -104 and -105 (5 x 4 KB @ $4000-$8FFF); verified
 * against the 64K image (disasm/build/spacduel_64k.bin).
 * Carried as DATA for the self-test's ROM checksum loop
 * ($8244 EorCksumRoms) and the signature-analysis table
 * copies ($8D85) - see selftest.c. Do not edit - regenerate. */
#ifndef SD_PROGROM_H
#define SD_PROGROM_H

#include <stdint.h>

#define SD_PROGROM_BASE 0x4000u   /* CPU address of sd_progrom[0] */
#define SD_PROGROM_SIZE 0x5000u

extern const uint8_t sd_progrom[0x5000];

#endif /* SD_PROGROM_H */
