/* sd_vecrom.h - Space Duel vector ROM image, CPU $2800-$3FFF.
 * generated by c_src/tools/gen_vecrom.py from ROMs 136006-106
 * (2 KB @ $2800) and 136006-107 (4 KB @ $3000); verified
 * against the 64K image (disasm/build/spacduel_64k.bin).
 * $2800-$2FFF is the ship-picture table (not AVG data);
 * $3000-$3FFF is the AVG vector ROM (glyphs at $324A/$3458, shapes).
 * Do not edit - regenerate. */
#ifndef SD_VECROM_H
#define SD_VECROM_H

#include <stdint.h>

#define SD_VECROM_BASE 0x2800u   /* CPU address of sd_vecrom[0] */
#define SD_VECROM_SIZE 0x1800u

extern const uint8_t sd_vecrom[0x1800];

#endif /* SD_VECROM_H */
