[main]
vsync=0
dropped_frame_irqs=7
dropped_frame_hold_ms=0.000000
refresh_hz=0.000000
fps_lock=62.500000
;62.50000
[vector]
;phosphor_ms=12.000000
phosphor_ms=0.000000
linewidth=2.000000
gain=0
line_smoothing=0.700000
corner_strength=1.000000
fire_point_size=10.000000
[joystick]
deadzone=19

[sound]
pokey_volume=100
samples=1
pokey_skip=1
[dips]
lives=3
difficulty=normal
language=english
bonus_life=10000
coinage=1_coin_1_play
right_coin=x1
center_coin=x1
bonus_coins=none

