/* sound_data.h - Space Duel AS2SAC sound module ROM bytes, CPU $703C-$7419.
 * generated by c_src/tools/gen_sound_data.py from the 64K image
 * (disasm/build/spacduel_64k.bin) [$703C:$741A]; spot-checked
 * against the annotated listing.
 * Do not edit - regenerate. */
#ifndef SOUND_DATA_H
#define SOUND_DATA_H

#include <stdint.h>

#define SD_SNDROM_BASE 0x703Cu  /* CPU address of sd_sndrom[0] */
#define SD_SNDROM_SIZE 0x3DEu

extern const uint8_t sd_sndrom[0x3DE];

/* read a sound-module ROM byte by CPU address */
#define SNDROM(a)  (sd_sndrom[(uint16_t)(a) - SD_SNDROM_BASE])

#endif /* SOUND_DATA_H */
